#!/usr/bin/env bash

# Visualize network bandwidth on a host

declare -A DATA=()

fatal() {
	echo '[FATAL]' "@" >&2
	exit 1
}

mapfile -s 2 -t  lines < /proc/net/dev || fatal 'failed to read proc device'

while true; do
	for line in "${lines[@]}"; do 
		
		read -ra info <<< "$line"

		iface=${info[0]%:}
		rx_bytes=${info[1]%:}
		tx_bytes=${info[9]%:}

		old=${DATA[$iface]}
		DATA[$iface]="$rx_bytes $tx_bytes"	
		if [[ -z $old ]]; then
			echo "> $iface old data not found"
			continue
		fi

		read -r old_rx_bytes old_tx_bytes <<< "$old"

		d_rx_bytes=$((rx_bytes - old_rx_bytes))
		d_tx_bytes=$((tx_bytes - old_tx_bytes))
		d_total_bytes=$((d_rx_bytes + d_tx_bytes))

		echo "$iface: $d_rx_bytes $d_tx_bytes $d_total_bytes"
	done
	sleep 1
done
